# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'e0ea80b3-1689-4095-a11f-4b46d936e200'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'eldhosresgroup'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'eldhoabe/Sample_Application/azuredeploy.json'
    overrideParameters: '--webappName ciwebapp'
    deploymentMode: 'Incremental'
